# Классификация, регрессия, алгоритмы Data Mining с использованием R

## Аннотация

Наряду с сайтом <http://www.ievbras.ru/ecostat/Kiril/R/DM/>, этот репозиторий является вторым официальным местом публикации электронной книги _Шитиков В.К., Мастицкий С.Э. (2017) "Классификация, регрессия, алгоритмы Data Mining с использованием R"_.

В книге описана широкая совокупность методов построения статистических моделей классификации и регрессии для откликов, измеренных в альтернативной, категориальной и метрической шкалах. Подробно рассматриваются деревья решений, машины опорных векторов с различными разделяющими поверхностями, нелинейные формы дискриминантного анализа, искусственные нейронные сети и т.д. Показана технология применения таких методов бутстреп-агрегирования деревьев решений, как бэггинг, случайный лес и бустинг. Представлены различные методы построения ансамблей моделей для коллективного прогнозирования. Особое внимание уделяется сравнительной оценке эффективности и поиску оптимальных областей значений гиперпараметров моделей с использованием пакета `caret` для статистической среды R. Рассматриваются такие алгоритмы Data Mining, как генерация ассоциативных правил и анализ последовательностей. Отдельная глава посвящена методам многомерной ординации данных и различным алгоритмам кластерного анализа.

Описание методов статистического анализа сопровождается многочисленными примерами из различных областей на основе общедоступных исходных данных. Представлены несложные скрипты на языке R, дающие возможность читателю легко воспроизвести все расчеты.

Книга может быть использована в качестве учебного пособия по статистическим методам для студентов и аспирантов высших учебных заведений.

## Структура репозитория

Репозиторий разбит на следующие директории:

* `Book`: содержит PDF-файл книги (`Shitikov_Mastitsky_2017_DM_R.pdf`), а также приложение "Справочная карта по Data Mining" (`Shitikov_Mastitsky_2017_DM_R_Appendix.pdf`);
* `Data`: файлы с данными, необходимыми для воспроизведения приведенных в книге примеров;
* `Scripts`: листинги кода на языке R к каждой главе, а также папка со сторонними модулями (`Extra_Modules`).

## Онлайн-версия книги

Помимо файлов, содержащихся в папке `Book`, книга опубликована также в виде отдельного сайта по адресу <https://ranalytics.github.io/data-mining/>

Обратите внимание на то, что содержимое онлайн-версии книги *может незначительно отличаться* от содержимого соответствующего PDF файла. Например:

* результаты некоторых вычислений представлены в онлайн-версии более полно;
* имеют место небольшие различия в результатах описываемых вычислений, что обусловлено эффектом генератора случайных чисел;
* имеют место различия в форматировании текста и рисунков.

Однако перечисленные различия не принципиальны и никоим образом не влияют на понимание излагаемого материала.

## Условия распространения

Книга распространяется в электронном виде в рамках лицензии Creative Commons ["Атрибуция - Некоммерческое использование - На тех же условиях 4.0 Всемирная"](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru).

© 2017, Владимир Кириллович Шитиков, Сергей Эдуардович Мастицкий

## Контактная информация

В.К. Шитиков  
Институт экологии Волжского бассейна РАН  
г. Тольятти, ул. Комзина, 10  
Самарская обл., 445003, Россия  

E-mail:  
<stok1946@gmail.com>,  
<rtutorialsbook@gmail.com>

Сайты авторов:  
<http://www.ievbras.ru/ecostat/Kiril>  
<http://r-analytics.blogspot.com>
